/* ═══════════════════════════════════════════════════════════════════
   build.js — regenerates opportunities.js from opportunities.data.json
   ───────────────────────────────────────────────────────────────────
   opportunities.data.json is the SINGLE SOURCE OF TRUTH. Edit that,
   then run:  node build.js
   This script NEVER touches Erin's cloud data or the primary-device
   flag. It fails closed: any validation error = no files written.
   ═══════════════════════════════════════════════════════════════════ */
'use strict';
const fs = require('fs');
const cp = require('child_process');

const SRC  = 'opportunities.data.json';
const OUT  = 'opportunities.js';
const SNAP = '.opp_snapshot.json';

function fail(msg){ console.error('\n✗ BUILD FAILED — nothing written.\n  ' + msg + '\n'); process.exit(1); }

/* 1. Load master ------------------------------------------------------ */
let data;
try { data = JSON.parse(fs.readFileSync(SRC, 'utf8')); }
catch (e) { fail('Cannot parse ' + SRC + ': ' + e.message); }
if (!Array.isArray(data)) fail(SRC + ' must be a JSON array of opportunities.');

/* 2. Validate (fail closed) ------------------------------------------ */
const seen = {}, errs = [];
data.forEach(function (e, i) {
  const tag = (e && (e.id || e.title)) || ('#' + i);
  if (!e || typeof e !== 'object') { errs.push('#' + i + ' is not an object'); return; }
  if (!e.title || !String(e.title).trim()) errs.push(tag + ': missing title');
  if (!e.id || !String(e.id).trim()) errs.push(tag + ': missing id');
  else if (seen[e.id]) errs.push('duplicate id: ' + e.id);
  else seen[e.id] = 1;
  if (!e.cat && !e.type) errs.push(tag + ': missing cat/type');
  if (!(e.body || e.extbody || e.desc)) errs.push(tag + ': has no description (body/extbody)');
  if (!e.src) errs.push(tag + ': missing src');
});
if (errs.length) fail(errs.length + ' validation error(s):\n - ' + errs.slice(0, 40).join('\n - '));

/* 3. New / updated diff vs last snapshot ----------------------------- */
function sig(e){ return JSON.stringify([e.title,e.org,e.deadline,e.start,e.body,e.extbody,e.pills,e.cat,e.type]); }
let prev = null;
try { prev = JSON.parse(fs.readFileSync(SNAP, 'utf8')); } catch (e) { prev = null; }
const baseline = !prev || Object.keys(prev).length === 0;
const snap = {}, newIds = [], updIds = [];
data.forEach(function (e) {
  snap[e.id] = sig(e);
  if (baseline) return;                 // first build = baseline, nothing is "new"
  if (!(e.id in prev)) newIds.push(e.id);
  else if (prev[e.id] !== snap[e.id]) updIds.push(e.id);
});
const META = {
  sweptOn: new Date().toISOString().slice(0, 10),
  total: data.length,
  newIds: newIds,
  updatedIds: updIds
};

/* 4. Emit opportunities.js (UTF-8, NO BOM — Node default) ------------ */
const banner =
  '/* ═══════════════════════════════════════════════════════════════\n' +
  '   AUTO-GENERATED by build.js — DO NOT EDIT BY HAND.\n' +
  '   Edit ' + SRC + ' then run:  node build.js\n' +
  '   Generated: ' + META.sweptOn + '  ·  ' + data.length + ' opportunities\n' +
  '   ═══════════════════════════════════════════════════════════════ */\n';
const js = banner +
  'var ALL = ' + JSON.stringify(data) + ';\n' +
  'var ALL_META = ' + JSON.stringify(META) + ';\n';
fs.writeFileSync(OUT, js, { encoding: 'utf8' });

/* 5. Syntax self-check (revert? no — we only just wrote it; verify) -- */
try { cp.execSync('node --check ' + OUT, { stdio: 'pipe' }); }
catch (e) { fail('Generated ' + OUT + ' failed node --check (this is a bug in build.js): ' + e.message); }

/* 6. Cache-bust every page that loads opportunities.js --------------
   Version = date + count + content-hash, so ANY data change (even
   content-only, same count/day) forces browsers to refetch. */
const hash = require('crypto').createHash('sha1')
  .update(JSON.stringify(data)).digest('hex').slice(0, 8);
const ver = META.sweptOn.replace(/-/g, '') + '-' + data.length + '-' + hash;
let bumped = 0;
fs.readdirSync('.')
  .filter(function (f) { return /\.html$/.test(f) && !f.startsWith('mockup_') && !f.startsWith('_'); })
  .forEach(function (f) {
    const t0 = fs.readFileSync(f, 'utf8');
    const t1 = t0.replace(/src="opportunities\.js(\?v=[0-9a-z-]+)?"/g, 'src="opportunities.js?v=' + ver + '"');
    if (t1 !== t0) { fs.writeFileSync(f, t1, { encoding: 'utf8' }); bumped++; }
  });

/* 7. Persist snapshot for next diff --------------------------------- */
fs.writeFileSync(SNAP, JSON.stringify(snap, null, 1), { encoding: 'utf8' });

/* 8. Browse-page pass — PRESERVE existing cards verbatim, APPEND new ---
   Existing inter-marker bytes are NEVER reparsed or changed. Only
   snapshot-detected new ids (META.newIds) whose record.src is the page
   and which are not already present get a freshly rendered card appended
   inside that page's FIRST region (the client float-to-top script then
   surfaces s-new cards). A baseline build appends nothing → every page
   stays byte-for-byte identical (golden). Fail-soft per page: never
   corrupt a page; skip + report on any anomaly. Browse pages do not load
   opportunities.js, so step 6 never rewrote them. */
const BPAGES_F = 'browse.pages.json';
let BPAGES = [];
try { BPAGES = JSON.parse(fs.readFileSync(BPAGES_F, 'utf8')); } catch (e) { BPAGES = []; }
const BYID = {}; data.forEach(function (e) { BYID[e.id] = e; });
const MOJI = /Ã|Â|â€|ð\x9f|�/;
function bEsc(s){ return String(s==null?'':s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;'); }
function bDataItem(e){
  var o={title:e.title,org:e.org,type:e.type,cat:e.cat,src:e.src,src_label:e.src_label,
    deadline:e.deadline||'',start:e.start||'',body:e.body||'',badge:e.badge||'',pills:e.pills||[],id:e.id};
  return JSON.stringify(o).replace(/"/g,'&quot;');
}
function bCard(e, today){
  var fam = /erin_programs/.test(e.src) ? 'pc2' : 'pos-card';
  var links=(e.links||[]).map(function(l){return '<a class="sl2" href="'+bEsc(l.href)+'">'+bEsc(l.label)+'</a>';}).join('');
  var meta=[e.deadline?'<strong>Deadline:</strong> '+bEsc(e.deadline):'',
            e.start?'<strong>Start:</strong> '+bEsc(e.start):'',
            e.pay?'<strong>Pay:</strong> '+bEsc(e.pay):'',
            e.location?'<strong>Location:</strong> '+bEsc(e.location):''].filter(Boolean).join(' &middot; ');
  var more=e.more?('<button class="more-btn" onclick="toggleMore(this)">&#43; More info</button>'+
        '<div class="more-panel"><p>'+bEsc(e.more)+'</p>'+
        (e.contact?'<div class="contact-block">'+bEsc(e.contact)+'</div>':'')+'</div>'):'';
  var newb='<span class="status-badge s-new">&#10024; New &mdash; '+today+'</span> ';
  var save='<button class="ml-save-btn" data-id="'+bEsc(e.id)+'" data-item="'+bDataItem(e)+'">&#9734; Save to My List</button>';
  var badge=e.badge?'<span class="badge mg">'+bEsc(e.badge)+'</span>':'';
  if(fam==='pc2'){
    return '\n  <div class="pc2">\n'+
      '    <div class="ph2"><div><div class="pn">'+newb+bEsc(e.title)+'</div><div class="pl">'+bEsc(e.org)+'</div></div>'+badge+'</div>\n'+
      '    <div class="pb2">'+bEsc(e.body)+'</div>\n'+
      (links?'    <div class="slinks">'+links+'</div>\n':'')+
      (meta?'    <div style="font-size:12px;color:var(--t2);margin-bottom:.5rem">'+meta+'</div>\n':'')+
      '    '+more+'\n    '+save+'\n  </div>\n';
  }
  return '\n  <div class="pos-card hot">\n'+
    '    <div class="pos-header"><div><div class="pos-title">'+newb+bEsc(e.title)+'</div><div class="pos-org">'+bEsc(e.org)+'</div></div>'+badge+'</div>\n'+
    (meta?'    <div class="pos-meta">'+meta+'</div>\n':'')+
    '    <div class="pb2">'+bEsc(e.body)+'</div>\n'+
    (links?'    <div class="slinks">'+links+'</div>\n':'')+
    '    '+more+'\n    '+save+'\n  </div>\n';
}
const bAdded = [], bPagesChanged = [], bWarn = [];
let bManifestDirty = false;
BPAGES.forEach(function (pg) {
  let txt; try { txt = fs.readFileSync(pg.file, 'utf8'); } catch (e) { return; }
  const markCount = (txt.match(/<!--BR:[^>]+:(start|end)-->/g) || []).length;
  const present = {}; pg.regions.forEach(function (r) { r.ids.forEach(function (id) { present[id] = 1; }); });
  const toAdd = META.newIds.filter(function (id) {
    return BYID[id] && BYID[id].src === pg.file && !present[id];
  });
  if (!toAdd.length) return;                 // nothing new → page untouched (golden)
  const endTag = '<!--' + pg.regions[0].marker + ':end-->';
  const at = txt.indexOf(endTag);
  if (at === -1) { bWarn.push(pg.file + ': first end-marker missing — skipped'); return; }
  let inject = '';
  toAdd.forEach(function (id) { inject += bCard(BYID[id], META.sweptOn); });
  const next = txt.slice(0, at) + inject + txt.slice(at);
  if (next.charCodeAt(0) === 0xFEFF || MOJI.test(inject)) { bWarn.push(pg.file + ': BOM/mojibake in render — skipped'); return; }
  if ((next.match(/<!--BR:[^>]+:(start|end)-->/g) || []).length !== markCount) { bWarn.push(pg.file + ': marker count changed — skipped'); return; }
  fs.writeFileSync(pg.file, next, { encoding: 'utf8' });
  pg.regions[0].ids = pg.regions[0].ids.concat(toAdd);
  bManifestDirty = true;
  toAdd.forEach(function (id) { bAdded.push(BYID[id].title + ' [' + pg.file + ']'); });
  bPagesChanged.push(pg.file + ' (+' + toAdd.length + ')');
});
if (bManifestDirty) fs.writeFileSync(BPAGES_F, JSON.stringify(BPAGES, null, 2), { encoding: 'utf8' });

/* 9. Plain-English "what changed" digest for the weekly PR ----------- */
const bUpdated = META.updatedIds.map(function (id) { return BYID[id] ? BYID[id].title : id; });
const digest =
  '# Weekly opportunity sweep — ' + META.sweptOn + '\n\n' +
  '**Added ' + bAdded.length + ' new** ' + (bAdded.length === 1 ? 'opportunity' : 'opportunities') +
  (bAdded.length ? ':\n' + bAdded.map(function (t) { return '- ' + t; }).join('\n') : '.') + '\n\n' +
  '**Updated ' + bUpdated.length + '** (data changed; existing Browse card preserved verbatim — review and hand-tweak wording if needed)' +
  (bUpdated.length ? ':\n' + bUpdated.map(function (t) { return '- ' + t; }).join('\n') : '.') + '\n\n' +
  '**Total opportunities:** ' + data.length + '\n' +
  '**Browse pages updated:** ' + (bPagesChanged.length ? bPagesChanged.join(', ') : 'none (data-only / digest-only)') + '\n' +
  (bWarn.length ? '\n**⚠ Warnings:**\n' + bWarn.map(function (w) { return '- ' + w; }).join('\n') + '\n' : '') +
  '\nNothing is live until this PR is merged.\n';
fs.writeFileSync('SWEEP_DIGEST.md', digest, { encoding: 'utf8' });
META.added = bAdded.length; META.browsePagesChanged = bPagesChanged;

console.log('\n✓ BUILD OK');
console.log('  entries:   ' + data.length + (baseline ? '  (baseline snapshot created)' : ''));
if (!baseline) console.log('  new:       ' + newIds.length + (newIds.length ? '  [' + newIds.join(', ') + ']' : ''));
if (!baseline) console.log('  updated:   ' + updIds.length + (updIds.length ? '  [' + updIds.join(', ') + ']' : ''));
console.log('  cache ver: ' + ver + '  (opportunities.js?v= bumped on ' + bumped + ' page(s))');
console.log('  browse:    +' + bAdded.length + ' new card(s)' +
  (bPagesChanged.length ? ' on ' + bPagesChanged.join(', ') : ' (no Browse changes — existing pages byte-identical)'));
if (bWarn.length) console.log('  ⚠ browse warnings: ' + bWarn.join('; '));
console.log('  digest:    SWEEP_DIGEST.md written');
console.log('  Next: review changes, commit, push/PR to your branch.\n');
