/* ═══════════════════════════════════════════════════════════════════
   build.js — regenerates opportunities.js from opportunities.data.json
   ───────────────────────────────────────────────────────────────────
   opportunities.data.json is the SINGLE SOURCE OF TRUTH. Edit that,
   then run:  node build.js
   This script NEVER touches Erin's cloud data or the primary-device
   flag. It fails closed: any validation error = no files written.
   ═══════════════════════════════════════════════════════════════════ */
'use strict';
const fs = require('fs');
const cp = require('child_process');

const SRC  = 'opportunities.data.json';
const OUT  = 'opportunities.js';
const SNAP = '.opp_snapshot.json';

function fail(msg){ console.error('\n✗ BUILD FAILED — nothing written.\n  ' + msg + '\n'); process.exit(1); }

/* 1. Load master ------------------------------------------------------ */
let data;
try { data = JSON.parse(fs.readFileSync(SRC, 'utf8')); }
catch (e) { fail('Cannot parse ' + SRC + ': ' + e.message); }
if (!Array.isArray(data)) fail(SRC + ' must be a JSON array of opportunities.');

/* 2. Validate (fail closed) ------------------------------------------ */
const seen = {}, errs = [];
data.forEach(function (e, i) {
  const tag = (e && (e.id || e.title)) || ('#' + i);
  if (!e || typeof e !== 'object') { errs.push('#' + i + ' is not an object'); return; }
  if (!e.title || !String(e.title).trim()) errs.push(tag + ': missing title');
  if (!e.id || !String(e.id).trim()) errs.push(tag + ': missing id');
  else if (seen[e.id]) errs.push('duplicate id: ' + e.id);
  else seen[e.id] = 1;
  if (!e.cat && !e.type) errs.push(tag + ': missing cat/type');
  if (!(e.body || e.extbody || e.desc)) errs.push(tag + ': has no description (body/extbody)');
  if (!e.src) errs.push(tag + ': missing src');
});
if (errs.length) fail(errs.length + ' validation error(s):\n - ' + errs.slice(0, 40).join('\n - '));

/* 3. New / updated diff vs last snapshot ----------------------------- */
function sig(e){ return JSON.stringify([e.title,e.org,e.deadline,e.start,e.body,e.extbody,e.pills,e.cat,e.type]); }
let prev = null;
try { prev = JSON.parse(fs.readFileSync(SNAP, 'utf8')); } catch (e) { prev = null; }
const baseline = !prev || Object.keys(prev).length === 0;
const snap = {}, newIds = [], updIds = [];
data.forEach(function (e) {
  snap[e.id] = sig(e);
  if (baseline) return;                 // first build = baseline, nothing is "new"
  if (!(e.id in prev)) newIds.push(e.id);
  else if (prev[e.id] !== snap[e.id]) updIds.push(e.id);
});
const META = {
  sweptOn: new Date().toISOString().slice(0, 10),
  total: data.length,
  newIds: newIds,
  updatedIds: updIds
};

/* 4. Emit opportunities.js (UTF-8, NO BOM — Node default) ------------ */
const banner =
  '/* ═══════════════════════════════════════════════════════════════\n' +
  '   AUTO-GENERATED by build.js — DO NOT EDIT BY HAND.\n' +
  '   Edit ' + SRC + ' then run:  node build.js\n' +
  '   Generated: ' + META.sweptOn + '  ·  ' + data.length + ' opportunities\n' +
  '   ═══════════════════════════════════════════════════════════════ */\n';
const js = banner +
  'var ALL = ' + JSON.stringify(data) + ';\n' +
  'var ALL_META = ' + JSON.stringify(META) + ';\n';
fs.writeFileSync(OUT, js, { encoding: 'utf8' });

/* 5. Syntax self-check (revert? no — we only just wrote it; verify) -- */
try { cp.execSync('node --check ' + OUT, { stdio: 'pipe' }); }
catch (e) { fail('Generated ' + OUT + ' failed node --check (this is a bug in build.js): ' + e.message); }

/* 6. Cache-bust every page that loads opportunities.js --------------
   Version = date + count + content-hash, so ANY data change (even
   content-only, same count/day) forces browsers to refetch. */
const hash = require('crypto').createHash('sha1')
  .update(JSON.stringify(data)).digest('hex').slice(0, 8);
const ver = META.sweptOn.replace(/-/g, '') + '-' + data.length + '-' + hash;
let bumped = 0;
fs.readdirSync('.')
  .filter(function (f) { return /\.html$/.test(f) && !f.startsWith('mockup_') && !f.startsWith('_'); })
  .forEach(function (f) {
    const t0 = fs.readFileSync(f, 'utf8');
    var t1 = t0.replace(/src="opportunities\.js(\?v=[0-9a-z-]+)?"/g, 'src="opportunities.js?v=' + ver + '"');
    t1 = t1.replace(/src="site\.js(\?v=[0-9a-z-]+)?"/g, 'src="site.js?v=' + ver + '"');
    t1 = t1.replace(/src="priority\.js(\?v=[0-9a-z-]+)?"/g, 'src="priority.js?v=' + ver + '"');
    t1 = t1.replace(/href="styles\.css(\?v=[0-9a-z-]+)?"/g, 'href="styles.css?v=' + ver + '"');
    if (t1 !== t0) { fs.writeFileSync(f, t1, { encoding: 'utf8' }); bumped++; }
  });

/* 6b. Stamp the build hash into site.js (the cache-bust id; the
   user-facing release number is bumped later, only on real changes). */
try {
  var sjP = 'site.js', sj0 = fs.readFileSync(sjP, 'utf8');
  var sj1 = sj0.replace(/var WN_BUILD\s*=\s*'[^']*'\s*;/, "var WN_BUILD   = '" + ver + "';");
  if (sj1 !== sj0) fs.writeFileSync(sjP, sj1, { encoding: 'utf8' });
} catch (e) { console.error('  ⚠ site.js build stamp skipped: ' + e.message); }

/* 7. Persist snapshot for next diff --------------------------------- */
fs.writeFileSync(SNAP, JSON.stringify(snap, null, 1), { encoding: 'utf8' });

/* 8. Plain-English "what changed" digest for the weekly PR ----------
   The 4 Browse pages render straight from opportunities.js, so the sweep
   is DATA-ONLY: just summarise the snapshot diff. No page rewriting. */
const REC = {}; data.forEach(function (e) { REC[e.id] = e; });
function fitTier(b){ b=(b||'').toLowerCase();
  if(/exception|top recommend/.test(b)) return 'Excellent';
  if(/strong/.test(b)) return 'Strong';
  if(/good|solid|verified open|open now/.test(b)) return 'Good';
  return 'Reach / review'; }
function line(id){ var e=REC[id]||{}; return '- ' + (e.title||id)
  + ' — _' + fitTier(e.badge) + '_'
  + (e.region ? ' · ' + e.region : '')
  + (e.deadline ? ' · deadline: ' + e.deadline : ''); }
const addedL = newIds.map(line);
const updL   = updIds.map(line);
const review = newIds.filter(function (id) { return fitTier((REC[id]||{}).badge) === 'Reach / review'; }).map(line);
const digest =
  '# Weekly opportunity sweep — ' + META.sweptOn + '\n\n' +
  '**Added ' + addedL.length + ' new** ' + (addedL.length === 1 ? 'opportunity' : 'opportunities') +
  (addedL.length ? ':\n' + addedL.join('\n') : '.') + '\n\n' +
  (review.length ? '**⚠ Review these (reach / weak fit — your call whether to keep):**\n' + review.join('\n') + '\n\n' : '') +
  '**Updated ' + updL.length + '** (deadline / status / description changed)' +
  (updL.length ? ':\n' + updL.join('\n') : '.') + '\n\n' +
  '**Total opportunities:** ' + data.length +
  '  ·  next-cycle: ' + data.filter(function(e){return e.cycle==='next';}).length +
  '  ·  expired (one-time, no future cycle): ' + data.filter(function(e){return e.expired===true;}).length + '\n' +
  'Triage: passed-but-recurring → `cycle:"next"`; one-time/discontinued → `expired:true`. ' +
  'Passed/expired are hidden on the site by default (toggle to show); never deleted, never moved to the personal Archive. ' +
  'Fit tiers: _Excellent_ / _Strong_ / _Good_ / _Reach / review_ (set via each entry\'s badge). ' +
  'The Browse pages render from this data automatically — no HTML edits. ' +
  'Nothing is live until this PR is merged.\n';
fs.writeFileSync('SWEEP_DIGEST.md', digest, { encoding: 'utf8' });

console.log('\n✓ BUILD OK');
console.log('  entries:   ' + data.length + (baseline ? '  (baseline snapshot created)' : ''));
if (!baseline) console.log('  new:       ' + newIds.length + (newIds.length ? '  [' + newIds.join(', ') + ']' : ''));
if (!baseline) console.log('  updated:   ' + updIds.length + (updIds.length ? '  [' + updIds.join(', ') + ']' : ''));
console.log('  cache ver: ' + ver + '  (opportunities.js?v= bumped on ' + bumped + ' page(s))');
console.log('  digest:    SWEEP_DIGEST.md written');

/* 10. Auto-deploy: bump release, commit, push to main.
   Release number (1.00, 1.01, 1.02, …) bumps ONLY when there's something
   real to deploy — running build.js with no source changes does NOT bump.
   The bump is computed AFTER staging so the commit captures the new
   release number + writes version.json + patches site.js's WN_VERSION. */
(function deploy(){
  try { cp.execSync('git rev-parse --is-inside-work-tree', { stdio: 'pipe' }); }
  catch (e) { console.log('  deploy:   skipped (not a git repo here)'); return; }
  try {
    cp.execSync('git add -A', { stdio: 'pipe' });
    var status = '';
    try { status = cp.execSync('git diff --cached --name-only', { encoding: 'utf8' }); } catch (e) {}
    if (!status.trim()) { console.log('  deploy:   no changes to commit; skipping push'); return; }

    /* Bump the human release number (1.xx). */
    var prevRelease = null;
    try { prevRelease = JSON.parse(fs.readFileSync('version.json', 'utf8')).release; } catch (e) {}
    var nextRelease;
    if (prevRelease == null || !/^\d+\.\d+$/.test(String(prevRelease))) {
      nextRelease = '1.00';
    } else {
      nextRelease = (Math.round((parseFloat(prevRelease) + 0.01) * 100) / 100).toFixed(2);
    }

    /* Patch site.js WN_VERSION = release number (cache hash already stamped
       earlier into WN_BUILD). */
    try {
      var sjP = 'site.js', sj0 = fs.readFileSync(sjP, 'utf8');
      var sj1 = sj0.replace(/var WN_VERSION\s*=\s*'[^']*'\s*;/, "var WN_VERSION = '" + nextRelease + "';");
      if (sj1 !== sj0) fs.writeFileSync(sjP, sj1, { encoding: 'utf8' });
    } catch (e) {}

    /* version.json — machine-readable record */
    fs.writeFileSync('version.json', JSON.stringify({
      release: nextRelease, build: ver, builtAt: new Date().toISOString(),
      total: data.length, newCount: newIds.length, updatedCount: updIds.length,
      hash: hash, date: META.sweptOn
    }, null, 2), { encoding: 'utf8' });

    /* re-stage so the bump is included in the same commit */
    cp.execSync('git add -A', { stdio: 'pipe' });

    var msg = 'Release v' + nextRelease + ' · build ' + hash +
              ' · ' + data.length + ' opps' +
              (newIds.length ? ' · +' + newIds.length + ' new' : '') +
              (updIds.length ? ' · ' + updIds.length + ' updated' : '');
    cp.execSync('git commit -q -m ' + JSON.stringify(msg), { stdio: 'pipe' });
    console.log('  release:  v' + nextRelease + '  (' + msg + ')');

    try {
      cp.execSync('git push origin HEAD:main', { stdio: 'pipe' });
      console.log('  deploy:   ✓ pushed to origin/main (Pages will rebuild in a few minutes)');
    } catch (e) {
      console.log('  ⚠ push failed (commit kept locally): ' + (e.stderr ? e.stderr.toString().trim().split('\n').pop() : e.message));
      console.log('              re-run `node build.js` to retry, or push manually.');
    }
  } catch (e) {
    console.log('  ⚠ deploy step error (build itself succeeded): ' + e.message);
  }
})();
console.log('');
